### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by Makhothi**

### CODE REVIEW

**Comment by tramoonyane** [comment]
Did you add unittests for both methods as was required by the task?

**Comment by Makhothi** [comment]
Yes

**Comment by tramoonyane** [comment]
Did you find any pycodestyle errors?

**Comment by Makhothi** [comment]
I didn't detect any Pycodestyle errors in your code, all the current tests are passing successfully.

**Comment by tramoonyane** [comment]
Thanks

**Comment by tramoonyane** [comment]
I was confused by the below last test
 
 @unittest.skipIf(models.storage_t == 'db', "not testing file storage")
    def test_count(self):
        """Test the count() function"""
        state = State()
        state.name = "State_name"
        storage = models.storage
        storage.new(state)
        storage.save()
        self.assertTrue(storage.count(State) > 0)
        
        i thought it was a duplication of the last test method before it in test_db_storage.py, but i realized it is the test count method and not the same with the one before it. Anyway thanks.

**Comment by Makhothi** [comment]
Thank you

**Comment by tramoonyane** [comment]
I did not see the notification for your new pull request.

**Pull request merged**
